### ISSUE TITLE
Figure 3.6

### ISSUE THREAD

**Issue by hurak** [sisl/algforopt-errata#1]
Figure 3.6, page 38: 

In the caption it is claimed that for n queries I_{n-1} = F_2 I_n. In agreement with (3.1), F_2=1, therefore, it must hold that I_{n-1} = I_n.

However, in the figure n=5 and it is explicitly written that I_4 = 2 I_5.

**Comment by tawheeler** [comment]
That appears to be a valid problem. Indices should be increased by one. Thanks!

**Comment by tawheeler** [comment]
This has been fixed in the manuscript and you have been added to the acknowledgements section. Thank you!
