### ISSUE TITLE
Repeated equation (18.17)

### ISSUE THREAD

**Issue by bilderbuchi** [sisl/algforopt-errata#10]
The equations (18.17) and (18.18) on page 325 are identical. As I cannot find an error in the surrounding transformations, I suspect a simple copy-paste duplication.

As far as I can tell, I have the first printing (at least there is no mention of printing at all).

Awesome book btw, I'm positively blown away by the very approachable presentation of the material! 
Also, :+1: on using Julia for the examples, that definitely was influencing my choice, as I wanted to get a feel for the language for quite some time.

The only thing I found myself wishing for was some material on the relative merits/advantages/drawbacks of the different approaches for different applications (maybe as a final chapter?). I'm not an expert in the field like you authors are, and if I'm doing optimisation in the future some basis for deciding which approach to investigate first would surely come in handy!

**Comment by mykelk** [comment]
Thanks so much! And thanks for catching this! We'll fix this within a couple days.

**Comment by bilderbuchi** [comment]
You're very welcome! 

I realised I should probably add a specific example to my final point: 
If I'm doing optimisation, let's say it's probably going to be on CFD/FEM simulations. Therefore, from what I know from the book, I'm quite sure that gradient/derivative-based methods are not relevant. However, what are the most promising options **in practice**/in the field, considering that getting one new data point takes hours to days, number of total evaluations is therefore gonna be small, but e.g. parallel evaluation of multiple points would not be unusual.

**Comment by mykelk** [comment]
Ah, got it. Chapter 1 provides an overview of the different chapters, and then the chapters are pretty disciplined in stating in their first paragraph the category of problem it aims to solve. Then the summary part outlines the different methods. Both Tim and I will continue to think about how to best discuss how real world problems are solved in the field. It may become tempting to bring in more discussion of modeling, but we are trying our best to avoid making the book about modeling and application. We want to keep the focus on algorithmic insights. Other (very long) books discuss specific engineering applications quite well.

**Comment by bilderbuchi** [comment]
> It may become tempting to bring in more discussion of modeling, but we are trying our best to avoid making the book about modeling and application. We want to keep the focus on algorithmic insights.

I see, fair enough, that makes perfect sense!

**Comment by tawheeler** [comment]
@mykelk So we are not allowed to change the equation labels between printings. Removing 18.18 (the duplicate) would change the equation labels. 

Some options:

- Keep it as is - but flag it for change in next re-pagination and numeration change.
- Remove eq 18.18 but somehow increment the equation counter such that we don't change the following equations. Would have to take care to keep pagination the same as well.
- Attempt to modify 18.18 so that it is a logical step between 18.17 and 18.19. I don't really see a useful way to do this.

**Comment by mykelk** [comment]
There are several equations before it in that block. Can we break out an additional step in one of the earlier ones?

**Comment by bilderbuchi** [comment]
The only thing I see is between 18.13 and 18.14, where you could expand the binomial expression in `E((f_hat - E(f))^2)` explicitly, to show in more detail how this leads to the `-E(f_hat)^2` term, e.g.
```
nu_hat = E((f_hat - E(f))^2)  (18.13)
= E(f_hat^2) - 2 E(f_hat E(f_hat)) + E(f_hat)^2  (18.14)
= E(f_hat^2) - E(f_hat)^2  (18.15)
...
```
Could be that you consider that step too trivial, though. 
18.14-18.16 equation counters would be incremented by one, then, but 18.18 and onwwards would stay the same.

**Comment by tawheeler** [comment]
Okay, sounds good. I sort of want to inject the one additional line:
![image](https://user-images.githubusercontent.com/3334079/69505606-9b0c6c80-0edf-11ea-9f75-afaa8c915104.png)
but this is a good compromise.

**Comment by tawheeler** [comment]
Done! Thank you!
