### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by bilderbuchi** [sisl/algforopt-errata#11]
Hi!

I noticed a couple of minor issues (formatting etc):

* p 347, example 19.3: In the last array of equations, the right pair (starting with `x_7` and `x_9`) has too much space before the equals sign, probably due to a stretching hspace or something like that.
* p 376, Example 20.6: In the sentence "Next we sample a rule to apply to B.", the "B" is in the wrong font - `\mathcal` instead of `\mathbb`, is what I would suspect in Latex.
* p 402, Figure 21.11: I think the expression "f(v, s, r, p,..." is missing the `c^{(d)}` argument

**Comment by tawheeler** [comment]
Thank you for the comments!
The issue on p 347 is already fixed for the 2nd printing.
I addressed the other two, so those will come out in the third printing.

**Comment by mykelk** [comment]
Thanks @bilderbuchi and @tawheeler !

**Comment by bilderbuchi** [comment]
> The issue on p 347 is already fixed for the 2nd printing.

Ah ok. I checked in the readme first, isn't mentioned there.

**Comment by tawheeler** [comment]
I initially only filled out mathematical / theory / factual issues in the errata, and skipped formatting issues like extra spaces. Its not your fault. I'll start to include those as well.

**Comment by bilderbuchi** [comment]
I see, no problem. I am happy that I could help, in any case. :-)
