### ISSUE TITLE
page 183 Algorithm 10.2 error

### ISSUE THREAD

**Issue by stumarcus576** [sisl/algforopt-errata#12]
The final two lines in the for loop of Algorithm 10.2 augmented_lagrange_method on page 183 should be swapped. That is, the final two lines should be:
\lambda -= \rho * h(x)
\rho *= \gamma
The Lagrange multiplier estimate \lambda should be updated before the penalty factor \rho is increased.

**Comment by tawheeler** [comment]
Thank you - that is a sneaky little error. Fixed.

**Comment by mykelk** [comment]
Thanks so much!

**Comment by stumarcus576** [comment]
You can credit Stuart Rogers instead of stumarcus576.

**Comment by mykelk** [comment]
Done!
