### ISSUE TITLE
Typo on page 35 ?

### ISSUE THREAD

**Issue by VladislavAnkudinov** [sisl/algforopt-errata#13]
On page 35 it is stated "f is monotonically decreasing for x ≤ x∗ and monotonically increasing for x ≥ x∗" for unimodal function. Isn't it monotonically increasing for x ≤ x∗ as well as for x ≥ x∗ ?

**Comment by tawheeler** [comment]
"decreasing" and "increasing" are interpreted in the direction of positive x. For x <= x^*, the function is reducing in value as it moves toward x^*. For x >= x^*, the function is increasing in value as it moves away from x^*.
