### ISSUE TITLE
Alg. 4.4: Convex.jl API change

### ISSUE THREAD

**Issue by rbalexan** [sisl/algforopt-errata#15]
I am using Julia 1.4 with `] status` for Convex.jl as `[f65535da] Convex v0.13.3`

I tried to code up and run Algorithm 4.4 as written in the second printing, but it throws an argument error for the `solve!` function. Apparently the Convex.jl API changed in a recent version. From `? solve!`, both methods of `solve!` now require an `optimizer`:
```
# 2 methods for generic function "solve!":
  [1] solve!(problem::Problem{T}, optimizer::MathOptInterface.ModelLike; check_vexity, verbose, warmstart) where T in Convex at /Users/rba/.julia/packages/Convex/v9Ehz/src/solution.jl:204
  [2] solve!(problem::Problem{T}, optimizer; kwargs...) where T in Convex at /Users/rba/.julia/packages/Convex/v9Ehz/src/solution.jl:192
```

They have updated the syntax to `solve!(p, solver)` according to [this commit](https://github.com/JuliaOpt/Convex.jl/commit/a8e64d4f0dfb4147f435a039c3ccbf0fd36d52b). The suggested solver interface using SCS.jl is given in Convex.jl's [news](https://github.com/JuliaOpt/Convex.jl/blob/master/NEWS.md). 

I changed the following in Algorithm 4.4 and everything seems to work as expected.
- `using Convex` to `using Convex, SCS`
- `solve!(p)` to `solve!(p, SCS.Optimizer(verbose=false))`

**Comment by mykelk** [comment]
Thanks! @tawheeler should we try to track this API change? It seems like it would be a good idea, but I'd like your input. We don't have too many dependencies, so it shouldn't be too hard.

**Comment by tawheeler** [comment]
We don't have that many dependencies and it is well worth keeping this up-to-date where we can.

**Comment by tawheeler** [comment]
FWIW I know this issue exists and will eventually address it

**Comment by tawheeler** [comment]
Fixed!
