### ISSUE TITLE
DIRECT example 7.2 center values (incorrect)

### ISSUE THREAD

**Issue by mossr** [sisl/algforopt-errata#20]
Chapter 7, page 122, example 7.2 for DIRECT: the values for the `center` column in the table show 0.25 and 0.75, when the actual centers are at 1/6 and 5/6, respectively (unless I'm misinterpreting something).

e.g., the center for interval 1 says [0.25, 0.50] when the actual center is [1/6, 1/2].

**Comment by mykelk** [comment]
Yes, I think you're right. I'll fix this. @tawheeler you agree?

**Comment by tawheeler** [comment]
That's right!
