### ISSUE TITLE
Footnote looks like exponent

### ISSUE THREAD

**Issue by mossr** [sisl/algforopt-errata#21]
Chapter 8, page 125, the use of a footnote superscript makes it look like an exponent in the inline equation: 

> ...typically a decreasing sequence σ⁽ᵏ⁾ such as 1/k.³

This makes it look like it's 1/k³ (cubed), when it's just 1/k

**Comment by mykelk** [comment]
The punctuation should make it unambiguous, though in the future we'll try to avoid this.
