### ISSUE TITLE
Example 8.1 caption: L1 –> L_inf norm

### ISSUE THREAD

**Issue by rbalexan** [sisl/algforopt-errata#23]
Related to the caption – I think all the directions in the positive spanning sets in Example 8.1 have unit l-infinity norms rather than unit l-one norms, right?

**Comment by mykelk** [comment]
Yep, I agree. I can fix this. @tawheeler do you agree?

**Comment by tawheeler** [comment]
I agree that those are I-infinity norms.
However, the caption is trying to get at the fact that components are all in {-1,0,1}. The direction [1.0,0.5] would also have an infinity norm of 1, but would not be what we are getting at. 
What if we just delete "\ell_1 - length"?

**Comment by mykelk** [comment]
Good idea.
