### ISSUE TITLE
Second line_search in Powell's method

### ISSUE THREAD

**Issue by mykelk** [sisl/algforopt-errata#25]
In alg. 7.4 on line 102, the **second** instance of `line_search` should probably have x' instead of x. It doesn't matter for fig. 7.4 since we are doing pretty much exact line search, but I think the real algorithm should probably do the search starting from the end point. Right @tawheeler ?

**Comment by mykelk** [comment]
Issue identified by Kaijun Feng.

**Comment by tawheeler** [comment]
thank you for checking. That does look like an x' is needed.
