### ISSUE TITLE
Eq. 8.3

### ISSUE THREAD

**Issue by mraitor** [sisl/algforopt-errata#27]
In eq 8.3 in section 8.2, defining the set from which the lower triangular components of L are sampled, the ere is no description of the {+1, + 2....-1} constants that appear. this pattern if left undefined could be any positive integer , z, added to -sqrt(alpha^(k)), e.g. -sqrt(alpha^(k)) + z, or subtracted from sqrt(alpha^(k)), e.g. sqrt(alpha^(k)) - z.

**Comment by tawheeler** [comment]
Sorry, I don't see this as sufficiently confusing to need a change. Eq 8.3 follows the convention of being in increasing order. The diagonal elements are drawn from pm 1/sqrt(alpha), whereas the lower terms come from all integers between -1/sqrt(alpha) and +1/sqrt(alpha). This is what is in the code too, with L[i,j] = rand(-delta+1 : delta-1). This is what it has to be if, as the text says, the maximum magnitude among the resulting directions is 1/sqrt(alpha).
