### ISSUE TITLE
Possible typo in Chapter 9

### ISSUE THREAD

**Issue by jcreus** [sisl/algforopt-errata#3]
I might be completely missing something but in page 160 of the printed book, the last paragraph says it's desirable to avoid equation (9.8) due to a singularity at $r=0$. However, (9.8) is $e^{-\gamma r}$, which is well behaved at zero; I suspect it refers to (9.7), i.e. $1/r^2$, which does have a singularity at zero.

**Comment by mykelk** [comment]
Thanks!
