### ISSUE TITLE
rand_positive_spanning_set

### ISSUE THREAD

**Issue by mykelk** [sisl/algforopt-errata#33]
Alg. 8.2 seems to have an issue with the construction of D. There seems to be some no-ops going on here:
```julia
D = L[randperm(n),:]
D = L[:,randperm(n)]
```

**Comment by zsunberg** [comment]
Were you expecting D to be a view of L? The current behavior is to make a
copy, but I think some version long ago it acted like a view

(Sent from phone)

**Comment by mykelk** [comment]
Even so, shouldn't the second line have a D on the right hand side?

**Comment by tawheeler** [comment]
Right. That's an easy fix.
