### ISSUE TITLE
o instead of 0

### ISSUE THREAD

**Issue by remzawi** [sisl/algforopt-errata#35]
Hi! I don't know if it has been signaled and corrected yet because it might be a small typo (doesn't appear in the errata), but isn't there a letter o instead of number 0 at the end of 17.3.4 page 316?

**Comment by remzawi** [comment]
(I'm not sure it's just that the form seems really close to the o just next to it)

**Comment by tawheeler** [comment]
The 'o' in 'to' is actually different from the zero 'o'. They juts look similar. Thanks for checking though!
