### ISSUE TITLE
Issue with expected improvement

### ISSUE THREAD

**Issue by mykelk** [sisl/algforopt-errata#37]
There is an issue in the step from eq. 16.11 to 16.12.
![image](https://user-images.githubusercontent.com/6294079/82257591-273aa200-990d-11ea-9ef8-13751e940ea7.png)
Hence, the first appearance of sigma hat in eq. 16.12 should be squared. This correction should be propagated to Alg. 16.2. The sigma on line 4 should be squared.

Thanks to Philippe Weingertner! @tawheeler , if you agree, I can implement this fix.

**Comment by tawheeler** [comment]
Hmm, there is no sigma squared terms in other derivations of the expected improvement. That must not be all that is wrong.

I think the issue is that 16.9 should be using u_hat and sigma_hat squared in the normal distribution. If this is propagated through it looks like we get the right answer.

@mykelk do you agree?

**Comment by mykelk** [comment]
I agree that it would get propagated through to get what's in the book, but I think N(z | 0, 1) is correct in 16.9. The definition of z is such that it is a zero-mean Gaussian.

What other derivations are you referring to?

**Comment by tawheeler** [comment]
> I agree that it would get propagated through to get what's in the book, but I think N(z | 0, 1) is correct in 16.9. The definition of z is such that it is a zero-mean Gaussian.

If I use z sampled from mu_hat and sigma_hat instead of z sampled from a zero-mean unit Gaussian, it looks like the math works.

> What other derivations are you referring to?
If you google expected improvement, various results I checked matched eq 16.12

**Comment by mykelk** [comment]
If we sample z from mu_hat and sigma_hat, then what is the point of the transformation in 16.7? Isn't y sampled from mu_hat and sigma_hat? It is reassuring that we match other references, but I'm still struggling on the reason.

**Comment by tawheeler** [comment]
I'm just telling you that the end result is right. We either have to figure out what is wrong in the middle.

![IMG_2290](https://user-images.githubusercontent.com/3334079/82346414-4720a300-99ab-11ea-91a9-324eae4033e7.jpg)

**Comment by tawheeler** [comment]
I'll take a closer look again this weekend at the latest.

**Comment by tawheeler** [comment]
The only way this works out is if the first term also has a missing sigma. The transformation for the cdf term from z to y must also produce such a sigma.

**Comment by PhilippeW83440** [comment]
I am attaching my derivation starting from Eq 16.11
Let me know if you see a problem (sorry for handwriting, I can type it in latex if it is not readable)

[EI.pdf](https://github.com/sisl/algforopt-errata/files/4658225/EI.pdf)

**Comment by PhilippeW83440** [comment]
I fixed a typo
[EI_fixed_typo.pdf](https://github.com/sisl/algforopt-errata/files/4658405/EI_fixed_typo.pdf)

**Comment by PhilippeW83440** [comment]
Attached a test program in EI.zip to compare the output of the different formulas (16.11, 16.12 and 16.12 modified), with associated plots

[EI.zip](https://github.com/sisl/algforopt-errata/files/4658567/EI.zip)
![EI_1611](https://user-images.githubusercontent.com/24230039/82481272-5e5baf80-9ad5-11ea-8040-1f83ead96fda.png)
![EI_1612](https://user-images.githubusercontent.com/24230039/82481289-6156a000-9ad5-11ea-93ee-1d6ae567fd28.png)
![EI_1612_modified](https://user-images.githubusercontent.com/24230039/82481300-64519080-9ad5-11ea-9a7f-345ae28f3456.png)

**Comment by PhilippeW83440** [comment]
I changed the name of 1 function in EI.jl: the name was misleading. But other than that, no change.
[EI.zip](https://github.com/sisl/algforopt-errata/files/4658636/EI.zip)

**Comment by tawheeler** [comment]
> I fixed a typo EI_fixed_typo.pdf

Is the 2nd-to-last step missing adding a sigma to the first term to counteract the division by sigma inside the integral? That would be the sigma I think we're missing. Otherwise the units don't match.

**Comment by tawheeler** [comment]
I don't understand why the units of expected improvement would be y squared.
If we have an improvement, say in meters, we wouldn't think of the expected improvement to be in meters squared.

**Comment by PhilippeW83440** [comment]
The extra sigma is there as well:
cf https://en.wikipedia.org/wiki/Normal_distribution 
Section on General normal distribution
https://wikimedia.org/api/rest_v1/media/math/render/svg/29ad1537690c6dca78c0a0834983bcd08c085aaf

**Comment by tawheeler** [comment]
The unit issue is resolved!
It is because the PDF is not unitless - it has units of 1 / sigma. Thus we _do_ have to include the extra sigma to cancel that out.

**Comment by tawheeler** [comment]
This change will affect a number of figures.

**Comment by tawheeler** [comment]
This turned out to only affect that one figure.
Fixed!
Thank you @PhilippeW83440 - this was a very good one to catch.

**Comment by mykelk** [comment]
Thanks so much @PhilippeW83440 !!!
