### ISSUE TITLE
Missing exp(1) in Algorithm B.1, page 426.

### ISSUE THREAD

**Issue by chaw** [sisl/algforopt-errata#4]
The code for Algorithm B.1 on page 426 seems to be missing a "exp(1)" after the last + sign.

**Comment by mykelk** [comment]
Oh, wow, good catch! It looks like the euler constant (generated by `\euler` within Julia) was used in the source code, but surprisingly the DejaVu Sans Mono font doesn't seem to support this symbol; see [this](http://www.fileformat.info/info/unicode/font/dejavu_sans_mono/list.htm), though the non-monospaced version does support EULER CONSTANT. I think it is Unicode U+2107. @tawheeler what do you recommend? Just go with `exp(1)`?

**Comment by mykelk** [comment]
Also, it doesn't show up in print elsewhere in the book, so that is a relief.

**Comment by tawheeler** [comment]
Fixed!
