### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by mindaugas-k** [sisl/algforopt-errata#42]
First printing, pg. 313, example 17.3: shouldn't the function be f(x,z)=x^2 + 6*exp(-x^2)? The value at x=0 is 6.

**Comment by mykelk** [comment]
Wow, good eye. You are right.

**Comment by tawheeler** [comment]
@mindaugas-k Would you like to be added to the acknowledgements section? What is your name?

**Comment by tawheeler** [comment]
(now fixed)

**Comment by mindaugas-k** [comment]
Yes of course if only you think that little error is worth it 😊 my name is
Mindaugas Kepalas and I am a phd student at Vilnius University in
Lithuania.
I would like to use the opportunity to thank you for the great book! It is
wonderfully written and I enjoy reading it so much!

**Comment by tawheeler** [comment]
Every contribution gets acknowledged!
Thank you!
