### ISSUE TITLE
Algorithm 8.1 in Page 126

### ISSUE THREAD

**Issue by Kelvyn88** [sisl/algforopt-errata#43]
I think the line 13 in the algorithm 8.1 miss the "*" operator.

σ = M.σ(M.k)

**Comment by mykelk** [comment]
Good question. The field `σ` is actually a function that takes as input the step number so that it can decease in size over time. For example, it can be `1/k` as mentioned under eq. (8.1). We can add an example of this in the next edition.

**Comment by Kelvyn88** [comment]
Thanks
