### ISSUE TITLE
example 10.5 on P179

### ISSUE THREAD

**Issue by yingjieMiao** [sisl/algforopt-errata#5]
This problem minimizes sin(x) over an interval. So the minimizer is either an endpoint or a stationary point. In fact, x* = -pi/2, p* = -1.

In the example's plot, u starts from 0.1. If we include u = 0, we would recover x*. 

A slightly more interesting example may be consider the constraint x^2 <= 1. Now the x* is found at a nontrivial u. (u = cos(1) / 2, if I got this correct.)

**Comment by tawheeler** [comment]
Is this what you meant?

![image](https://user-images.githubusercontent.com/3334079/59554365-a46bd300-8f56-11e9-8acc-3aed835c96ec.png)

The minimum in the original problem should be sqrt(3). I believe using 1.5 is a mistake.

**Comment by tawheeler** [comment]
Thanks @yingjieMiao, we will go with this.

**Comment by yingjieMiao** [comment]
Sorry for the late response - somehow I didn't get an email notification.

The original problem is minimized at a stationary point -pi/2. This corresponds to set u = 0 in the dual problem. (This u is "trivial" -- the Lagrangian happens to be sin(x) itself).

If we consider the constraint x^2 <= 1, sin(x) is monotonic on [-1, 1], it minimizes at -1. We could ask: in the dual problem, which u gives this minimizer?  

For a fixed u, set dL/dx = 0, we have cos(x) + 2*u*x = 0. If x=-1 is a stationary point, we solve u = cos(-1) / 2 = 0.270. (We can also verify the 2nd derivative > 0, so x = -1 is indeed a minimizer). This u is nontrivial.

Does this make sense?

**Comment by tawheeler** [comment]
Yes, this makes sense. The optimal `u` is no longer trivially at zero.
