### ISSUE TITLE
Explanation wrinkle in Algorithm 13.11, page 248.

### ISSUE THREAD

**Issue by chaw** [sisl/algforopt-errata#6]
Page 248, Algorithm 13.11.

Both the algorithm and the comment in the margin/caption (on the bound
for the kth prime) appear correct but, unless I am very confused, the
correctness of the algorithm does not follow very directly from the
bound.  Since the bound is valid for k > 6, the algorithm should be
testing n (and not the bound(n)) against 6.

Also, I believe the bound is valid for k=6 as well, based on ["Sharper
bounds...", P. Dusart, 1998].

The implementation will fail for m = 1, but that is a somewhat
perverse input.

**Comment by tawheeler** [comment]
I think the confusion is in the wording. It states that "The Primes package is used to generate the first n prime numbers". The sentence is slightly misleading. In the algorithm we use `primes` to generate the first n prime numbers, but calling primes(x) will give you all prime numbers up to x. If we want to guarantee that we get the first n prime numbers, we call primes(n*(log n + log log n)) or primes(6), whichever input is higher.

**Comment by tawheeler** [comment]
Updated in text and added to errata. Thanks!
