### ISSUE TITLE
Radians v degrees in Exercise 21.4

### ISSUE THREAD

**Issue by chaw** [sisl/algforopt-errata#7]
Exercise 21.4 specifiex theta_max as 10 rad, but I think it should be 10 degrees instead, given the wing-deformation context. 

I know very little about airplane design but I don't think I want to be in a plane whose wing deforms 10 radians. :-)  Besides, 10 degrees gives an answer that matches the solution in Appendix D.

**Comment by tawheeler** [comment]
Thank you!
