### ISSUE TITLE
Is julia step! function truly affecting the input arguments?

### ISSUE THREAD

**Issue by hurak** [sisl/algforopt-errata#8]
This is related to the Julia code (both in the book and in the corresponding Jupyter notebook): in the chapter on descent methods, there is a code snippet:
```julia
struct GradientDescent <: DescentMethod
    α
end

init!(M::GradientDescent, f, ∇f, x) = M

function step!(M::GradientDescent, f, ∇f, x)
    α, g = M.α, ∇f(x)
    return x - α*g
end
``` 
The `step!` function does not seem to affect the input arguments, why is there the exclamation mark in the name then? True, it is just a matter of [recommended style](https://docs.julialang.org/en/v1/manual/style-guide/#Append-!-to-names-of-functions-that-modify-their-arguments-1) but while trying to understand the code I find this issue confusing.

**Comment by tawheeler** [comment]
Good question. We only wanted to have a single method for descent methods. Some descent methods update internal state, so we used the bang (!). This way you don't have to remember whether to use `step` or `step!` for your `DescentMethod`.

**Comment by hurak** [comment]
> We only wanted to have a single method for descent methods. Some descent methods update internal state, so we used the bang (!). This way you don't have to remember whether to use `step` or `step!` for your `DescentMethod`.

Thanks for the explanation. Finally I also came to this conclusion that uniformity of names of functions was the reason. But when I first started thinking about the code, I confess that I allowed the bang symbol to confuse me and I started exploring for a few minutes if something is actually affected.
